<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            ['name' => 'SUV',      'icon' => 'heroicon-o-truck',        'sort_order' => 1],
            ['name' => 'Sedan',    'icon' => 'heroicon-o-car',          'sort_order' => 2],
            ['name' => 'Luxury',   'icon' => 'heroicon-o-star',         'sort_order' => 3],
            ['name' => 'Economy',  'icon' => 'heroicon-o-banknotes',    'sort_order' => 4],
            ['name' => 'Sports',   'icon' => 'heroicon-o-bolt',         'sort_order' => 5],
            ['name' => 'Electric', 'icon' => 'heroicon-o-battery-100',  'sort_order' => 6],
        ];

        foreach ($categories as $data) {
            // Slug is auto-generated by the Category model's creating event.
            Category::firstOrCreate(['name' => $data['name']], $data);
        }
    }
}
